(add-to-list 'load-path (expand-file-name "elisp"))
(require 'opencode-client)
(defun check (label got want)
  (princ (format "%s %s: got=%S want=%S\n" (if (equal got want) "PASS" "FAIL") label got want)))
(defun mk (seq part)
  (json-encode `((type . "sync") (syncEvent . ((type . "message.part.updated.1") (seq . ,seq) (data . ((part . ,part))))))))
(with-temp-buffer
  (opencode-client-mode)
  (setq opencode-client--parts (make-hash-table :test 'equal))
  (setq opencode-client--message-parts (make-hash-table :test 'equal))
  (let ((buf (current-buffer))
        (f1 (mk 1 '((id . "p1") (messageID . "m") (type . "text") (text . "Hello"))))
        (f2 (mk 2 '((id . "p1") (messageID . "m") (type . "text") (text . "Hello world"))))
        (f3 (mk 3 '((id . "p2") (messageID . "m") (type . "tool") (tool . "read") (state . ((status . "completed"))))))
        (stale (mk 1 '((id . "p1") (type . "text") (text . "STALE")))))
    (let* ((payload (concat "data: " f1 "\n\n")) (m (/ (length payload) 2)))
      (opencode-client--stream-filter buf nil (substring payload 0 m))
      (check "partial-no-apply" (hash-table-count opencode-client--parts) 0)
      (opencode-client--stream-filter buf nil (substring payload m)))
    (check "after-f1-parts" (hash-table-count opencode-client--parts) 1)
    (opencode-client--stream-filter buf nil (concat "data: " f2 "\n\ndata: " f3 "\n\n"))
    (check "after-f2f3-parts" (hash-table-count opencode-client--parts) 2)
    (check "seq" opencode-client--seq 3)
    (check "p1-upserted" (alist-get 'text (gethash "p1" opencode-client--parts)) "Hello world")
    (opencode-client--stream-filter buf nil (concat "data: " stale "\n\n"))
    (check "stale-text" (alist-get 'text (gethash "p1" opencode-client--parts)) "Hello world")
    (check "stale-seq" opencode-client--seq 3)
    (opencode-client--render)
    (princ "=== buffer ===\n") (princ (buffer-string))))
