import { readFile, writeFile } from "fs/promises"
import { dirname, join } from "path"
import { fileURLToPath } from "url"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const serverDir = dirname(scriptDir)
const elispPath = join(serverDir, "..", "emacs", "lisp", "mcp-emacs.el")
const outputPath = join(serverDir, "src", "bootstrap-elisp.ts")

const elispContent = await readFile(elispPath, "utf-8")
const payload = `(progn
${elispContent}
)`

const output = `// This file is generated by scripts/extract-elisp.js
export const bootstrapElisp = String.raw\`${payload}\`
`

await writeFile(outputPath, output, "utf-8")
